### ISSUE TITLE
El juego está muy avanzado, queda que el acertijo de las palancas funcione para abrir puertas y el jefe

### ISSUE THREAD

**Issue by Palaskan** [Palaskan/DungeonCocos2D#1]
Las palancas se pueden usar pero solo se puede una vez, si falla el acertijo, aparecen 3 enemigos, pero nunca está bien hecho porque falta hacer el orden para que funcione y se abra la puerta aunque lo tengo mas o menos hecho en código falta que se cumplan condiciones necesarias. 
También faltan las pociones y que se pueda recuperar vidas con ellas.
Y por último falta hacer al jefe y el modo de ataque y movimientos de éste.

**Comment by Lordland** [comment]
Jefe, pociones y movimientos y ataques del jefe hechos. Se da por cerrada esta funcionalidad-
